name: Rust

on:
  push:
    branches: [ "CICD_test" ]
  pull_request:
    branches: [ "CICD_test" ]
  workflow_dispatch: {}   # optional: allow manual runs from the Actions UI

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        sudo apt-get update
        # pkg-config is required for build.rs checks; libasound2-dev provides alsa.pc
        sudo apt-get install -y pkg-config libasound2-dev build-essential
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
